version: "3.1"

services:
  wordpress:
    image: wordpress
    restart: always
    ports:
      - 3339:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: marmishlag
    volumes:
      - ./wordpress:/var/www/html
  db:
    image: "mariadb"
    restart: always
    environment:
      MYSQL_DATABASE: marmishlag
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
